default_language_version:
  python: python3.12
repos:
  - repo: local
    hooks:
      - id: black
        name: "format"
        language: system
        entry: uv run black
        files: \.py$
      - id: pytest
        name: "test"
        language: system
        entry: uv run pytest
        files: \.py$|pyproject\.toml$
        pass_filenames: false
      - id: gh-gen
        name: "generate"
        language: system
        entry: uv run gh-gen
        files: \.py$|pyproject\.toml|\.yml$
        pass_filenames: false
